# Generated by Django 4.2.5 on 2023-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eqip_name", models.CharField(max_length=100)),
                ("volt", models.FloatField()),
                ("state", models.BinaryField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
